version: '3.1'

services:

  db:
    container_name: mariadb_server
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: classicmodels
    volumes:
      - "./sampleDB/:/docker-entrypoint-initdb.d"
    networks:
      - mysql

  adminer:
    container_name: dashboard
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mysql

networks:
  mysql:
